### ISSUE TITLE
firefox theme + cava

### ISSUE THREAD

**Issue by kaneru-soju** [lokesh-krishna/dotfiles#10]
Issues:

1. Firefox theme
- No firefox theme was posted to the repo, I was wondering if you could post your userchrome.css
2. Cava
- in .config/sway/config the app_id for cava doesn't exist by default. I'm wondering if you had a workaround for this.

**Comment by lokesh-krishna** [comment]
1. I am not using a custom `userChrome.css`, just a simple theme created on [Firefox Color](https://color.firefox.com/). You can (hopefully) apply it using this link: [Tokyo Night for Firefox](https://color.firefox.com/?theme=XQAAAAKPAgAAAAAAAABBqYhm849SCicxcUJJ2CuG_ebZUZXOFqpMUXOqPCZ36qSRJkXN52FbbTjiyK1MWFJNETZQ0wYF4uVCIywstutBMeAW7Obsj80UcPJQAnIVpdPOctZ5qwuxzdELFY4rFOFPOTJ56RTVDwA4OBpstebirCu7hY0081_kMAs5kyLOhcBXVznGEJZ8hLEKcsRDWIpmds_f9Bz4MLMjGF7kJmKEH1RnLL_dJvGnMgclfyzqTqHxYRhUWrgMfQmbcvGavbRFEetLZGVRbQ5P8k0F0PyfAFgTc6TBQIiKVQa2zX8gZ3Gru31J5KGfZrIaMw2B-eKScfJjrqEILop2n4DLLEe_lqL3ujDgM0Uv8i9nwGVvvQNj_vGGxQ)

2. I do :)  
I modified the `.desktop` file. The following should do the trick:  
```
Exec=kitty --class cava cava
```

**Comment by kaneru-soju** [comment]
Thanks for your help! I got it working.

For some reason, I can't get SwayLock to work properly with text. But that's alright. I'm still trying to figure it out
