### ISSUE TITLE
Absolute path is hardcoded

### ISSUE THREAD

**Issue by stiliajohny** [lokesh-krishna/dotfiles#12]
The following was found on the configs, 

I would suggest either make it relative path or reference it on your readme if is not applicable for the wofi app or doesn't accept relative paths

https://github.com/lokesh-krishna/dotfiles/blob/e371c3e1258f01441333f5838c4ffd7208fb3ca9/mountain/config/wofi/config#L1

**Comment by lokesh-krishna** [comment]
Good catch, I should have thought of it before making the files public. I'll close this issue once I've updated all absolute paths.

**Comment by stiliajohny** [comment]
might be a good idea to recursively search for `/home/loki/`
( I can telly ou if you open your `/home/loki` in vs ode and search in folder its the easier, 
either way you got to make a heavy command :)
