### ISSUE TITLE
Install/apply instructions

### ISSUE THREAD

**Issue by ThatOneCalculator** [lokesh-krishna/dotfiles#16]
Hi! I'm very new to sway, and some (even basic) instructions on how to install each of the themes would be great :)

**Comment by fhanrath** [comment]
Hello,

generally speaking you want to copy the contents of the config folder of the theme you want to your ~/.config folder.
There are a few exceptions. Eg the .zshrc file usually lives directly in your home directory.

I'd suggest you look up each program/part you want to use and how to configure it generally speaking. Then you can get back to this repo and take the appropriate config file/s and put them into the correct directory.

Maybe it would be best to create your own dotfiles repo with a script that puts every config into the correct location. This way you only have to do this work once and are able to incrementally adjust your settings to your liking.

- The Sway config lives under `~/.config/sway/conf`
- For waybar it's `~/.config/waybar/config` and `~/.config/waybar/style.css`

If you have any questions, feel free to ask.
