### ISSUE TITLE
Missing file for triggering notify-send (brightness, volume and etc)

### ISSUE THREAD

**Issue by thyeun** [lokesh-krishna/dotfiles#19]
Few ```sh``` files missing, especially for notify-send.

**Comment by lokesh-krishna** [comment]
Thanks for bringing this up!  
The brightness notifications are in sway's config. I've now uploaded the scripts for screenshots and volume :) 
Are there any other scripts that are missing or can this issue now be closed?

**Comment by thyeun** [comment]
@lokesh-krishna thank you so much :)
