### ISSUE TITLE
Cava config not working

### ISSUE THREAD

**Issue by Kranzes** [lokesh-krishna/dotfiles#2]
um im currently using your cava config and for some reason i dont have same result as you, i dont have the colorful gradient and all that cool stuff, do you use some kind of fork of cava?

**Comment by lokesh-krishna** [comment]
Hey,
I'm using [this package](https://aur.archlinux.org/packages/cava) from the AUR. The current version is 0.7.2-1.  
Could you tell me what terminal you're using and share a screenshot of what your cava looks like presently?
