### ISSUE TITLE
Neomutt config?

### ISSUE THREAD

**Issue by ksladowski** [lokesh-krishna/dotfiles#7]
That screenshot looks amazing but I don't see any configs for it

**Comment by Flyxi121** [comment]
I would also kindly appreciate it if you could upload the neomutt configuration!

**Comment by lokesh-krishna** [comment]
Sorry I took so long to get back to this. I am using mutt-wizard for my config with overrides over the defaults. I've added the [file](https://github.com/lokesh-krishna/dotfiles/tree/master/nord-v3/config/mutt) now :)
