### ISSUE TITLE
Font for Waybar Workspace and Battery Icons?

### ISSUE THREAD

**Issue by agonzalez777** [lokesh-krishna/dotfiles#8]
Hello! Love your theme. I am trying to figure out what font you are using for the battery icon and workspace icons in waybar. I have fontawesome installed, but it is still not rendering.. (just square boxes appear). Any help would be appreciated. Thanks again!

**Comment by agonzalez777** [comment]
Solved: Material Design Font worked!

**Comment by RaymondSchnyder** [comment]
> Solved: Material Design Font worked!

Didnt work for me, weird.
I installed ttf-material-design-icons from the Arch AUR but i still get squares

**Comment by lokesh-krishna** [comment]
Thanks for bringing this up. I've added a mention and a link to the readme now :)

**Comment by fhanrath** [comment]
@RaymondSchnyder did you find a solution to your problem? I'm on Arch and do have the same issue.

**Comment by RaymondSchnyder** [comment]
> @RaymondSchnyder did you find a solution to your problem? I'm on Arch and do have the same issue.

Sadly not, i just searched some icons that work on the internet and replaced the ones in this repo.
